### ISSUE TITLE
Error in the moon phase icons in the calendar

### ISSUE THREAD

**Issue by HermesAquila** [worldanvil/wa-calendar-issue-tracker#11]
**World Anvil Username**: Hermes_aquila

**World / Campaign / RPG Character / Manuscript Title**:   World: Lumaria

**Feature**: Calendars

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/lumaria-hermesaquila/a/calendario-article

**Describe the Issue**
The icons for the moons seem wrong. It only shows waxing icos, both in waning and waxing lunar phases. (Sorry for the text, the world is in spanish)

**To Reproduce**
1. Follow the URL
2. Just look at the moon icons in the calendar

**Expected behavior**
Waning ("menguante" in spanish) moon icons should be filled from the left.

Thank you for your time, and your awesome work!

**Comment by jonaswaeber** [comment]
hi this is a known issue with the calendar and will not be addressed until a more sustained solution is found for it. This can be fixed with CSS in the meantime.

see #5 or #9

**Comment by HermesAquila** [comment]
Thank you for the response. Where can I find help about how to use CSS for that?

**Comment by jonaswaeber** [comment]
```css
.user-css-calendar button[class*=Waning-] .moon {
    transform: rotate(180deg);
}
```
This was commented in one of the tickets. Otherwise ask on the Discord server in the #css-help channel

**Comment by HermesAquila** [comment]
Thanks!
